#!/bin/sh
./mkone
coursier launch -r "https://dl.bintray.com/tpolecat/maven/" org.tpolecat:tut-core_2.12:0.6.4 --   \
combine.md out '.*\.md$' -classpath $(coursier fetch -p com.chuusai:shapeless_2.12:2.3.3)
